// Shared types for the documentation viewer. Safe to import from both
// server and client components (no Node.js dependencies).

export type DocIconKey = "book" | "palette" | "layers" | "workflow" | "compass";

export interface TocHeading {
  /** Anchor id, identical to the one generated by rehype-slug. */
  id: string;
  /** Plain heading text (markdown stripped). */
  text: string;
  /** Heading level: 2 for sections, 3 for subsections. */
  depth: 2 | 3;
}

export interface DocMeta {
  /** Whitelisted slug used in the download API (/api/docs?file=slug). */
  slug: string;
  /** Path relative to the project root. */
  file: string;
  /** ASCII-safe file name for the Content-Disposition header. */
  fileName: string;
  title: string;
  subtitle: string;
  /** Short label used in the sidebar rail. */
  short: string;
  icon: DocIconKey;
  /** The main document (selected by default, visually emphasized). */
  primary: boolean;
}

export interface DocPayload extends DocMeta {
  content: string;
  toc: TocHeading[];
  lines: number;
  sections: number;
  words: number;
}
